// Pricing a subset page.
//
// 572 of the indexable URLs are a subset of a product — "2025 Panini Prizm /
// Rookie Revolution" — and `sales` has no subset column, so they cannot be
// joined by name the way products and players are. A subset IS a list of
// (player, card number) pairs, and a sale carries both, so the join goes
// through membership instead.
//
// Two things make that fragile, and both fail silently rather than loudly:
//
//   1. Inserts reuse the base set's numbering, so a (player, number) key can
//      belong to several subsets at once. Assigning one anyway puts one
//      subset's prices on another's page.
//
//   2. The key is built in two places — from a checklist entry in
//      build-landing-pages.js, and from SQL columns in server.js. If those two
//      normalisers disagree by so much as a hyphen, every lookup misses, no
//      error is raised, and the pages simply stay blank forever.
const fs = require('fs');
const path = require('path');
const { norm } = require(path.join(__dirname, '..', 'set-key.js'));

let failures = 0;
const check = (label, ok, detail) => {
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${label}${detail ? '  — ' + detail : ''}`);
  if (!ok) failures++;
};

const ROOT = path.join(__dirname, '..');
const attrPath = path.join(ROOT, 'public', 'data', 'subsets', 'attribution.json');

// ---- the two normalisers ----
//
// The SQL one is generated by _normCol(); the JS one is norm(). This
// reimplements _normCol's transformation in JS from its own source, so the
// check fails if either side changes without the other.
{
  const serverSrc = fs.readFileSync(path.join(ROOT, 'server.js'), 'utf8');
  const chars = serverSrc.match(/for \(const ch of \[([^\]]*)\]\) e = `REPLACE/);
  check('_normCol\'s character list was found in server.js', !!chars);

  if (chars) {
    // Parsed by matching quoted literals, NOT by splitting on commas — a
    // comma is itself one of the characters in that list, so splitting on it
    // tears the list apart and the first version of this check failed against
    // perfectly correct code.
    //
    // "''" is SQL's escaped single quote and means one apostrophe.
    const sqlChars = [...chars[1].matchAll(/"([^"]*)"|'([^']*)'/g)]
      .map(m => (m[1] !== undefined ? m[1] : m[2]))
      .map(x => (x === "''" ? "'" : x));
    const jsStrips = ["'", '.', ',', '"', '`', '’', '-'];
    check('  ...and matches what norm() strips, character for character',
      sqlChars.length === jsStrips.length && sqlChars.every((c, i) => c === jsStrips[i]),
      `SQL: ${JSON.stringify(sqlChars)}  JS: ${JSON.stringify(jsStrips)}`);

    // Applied to real data, not just compared as lists.
    const sqlNorm = (v) => {
      let e = String(v == null ? '' : v);
      for (const ch of sqlChars) e = e.split(ch).join('');
      e = e.toLowerCase().trim();
      for (let i = 0; i < 4; i++) e = e.split('  ').join(' ');
      return e.trim();
    };
    const samples = [
      "Ja'Marr Chase", 'Amon-Ra St. Brown', 'D.K. Metcalf', "Bowman's Best",
      'RC-1', '  spaced   out  ', 'Marvin Harrison Jr.', '',
    ];
    const disagree = samples.filter(v => sqlNorm(v) !== norm(v));
    check('  ...and produces the same string on real card data',
      disagree.length === 0,
      disagree.length
        ? disagree.map(v => `${JSON.stringify(v)}: SQL "${sqlNorm(v)}" vs JS "${norm(v)}"`).join(' | ')
        : `${samples.length} samples agree`);
  }
}

// ---- the artifact ----
if (!fs.existsSync(attrPath)) {
  console.log('SKIP  subset attribution map  — run `npm run build:pages` first (CI does)');
} else {
  const attr = JSON.parse(fs.readFileSync(attrPath, 'utf8'));
  const products = Object.keys(attr);
  const keys = products.reduce((n, id) => n + Object.keys(attr[id]).length, 0);

  check('the attribution map was built', products.length > 100 && keys > 10000,
    `${products.length} products, ${keys} card keys`);

  // Small enough for the daily cron to load. 27 MB of checklists is not, which
  // is the entire reason this artifact exists.
  const mb = fs.statSync(attrPath).size / 1024 / 1024;
  check('  ...and is small enough to load in a Worker', mb < 4, `${mb.toFixed(2)} MB`);

  // Every key must be `<normalised player>|<normalised number>`, because that
  // is exactly what server.js reconstructs from the SQL label.
  const bad = [];
  for (const id of products) {
    for (const k of Object.keys(attr[id])) {
      const at = k.indexOf('|');
      if (at === -1) { bad.push(`${id}: ${k} (no separator)`); break; }
      const p = k.slice(0, at), n = k.slice(at + 1);
      if (norm(p) !== p || norm(n) !== n) { bad.push(`${id}: ${k} (not normalised)`); break; }
    }
    if (bad.length > 3) break;
  }
  check('  ...with every key in the form server.js reconstructs',
    bad.length === 0, bad.slice(0, 3).join(' | ') || 'all well-formed');

  // The refusal. A key claimed by two subsets must be absent, not assigned.
  // Verified against the checklists themselves rather than trusted.
  {
    const dir = path.join(ROOT, 'public', 'data', 'checklists');
    const sample = products.slice(0, 25);
    let leaked = 0, checked = 0;
    for (const id of sample) {
      const file = path.join(dir, `${id}.json`);
      if (!fs.existsSync(file)) continue;
      const cl = JSON.parse(fs.readFileSync(file, 'utf8'));
      const sets = (cl.sets || []).filter(x => (x.cards || []).length >= 25);
      const owners = new Map();
      for (const x of sets) {
        for (const c of (x.cards || [])) {
          const k = `${norm(c.player)}|${norm(c.number)}`;
          owners.set(k, (owners.get(k) || 0) + 1);
        }
      }
      for (const k of Object.keys(attr[id])) {
        checked++;
        if ((owners.get(k) || 0) > 1) leaked++;
      }
    }
    check('a card belonging to two subsets is omitted, never guessed',
      leaked === 0,
      `${checked} keys checked across ${sample.length} products, ${leaked} ambiguous`);
  }

  // The pages have to carry a slot with the matching key shape.
  {
    const id = products[0];
    const slug = attr[id][Object.keys(attr[id])[0]];
    const page = path.join(ROOT, 'public', 'sets', id, slug, 'index.html');
    if (!fs.existsSync(page)) {
      console.log(`SKIP  subset slot on /sets/${id}/${slug}/  — page not built`);
    } else {
      const html = fs.readFileSync(page, 'utf8');
      const m = html.match(/data-price-key="([^"]+)"/);
      check('the subset page carries the key the cron writes',
        m && m[1] === `subset:${id}/${slug}`,
        m ? `page: ${m[1]}` : 'no slot on the page');
    }
  }
}

console.log(failures ? `\n${failures} check(s) failed` : '\nall subset-attribution checks passed');
process.exit(failures ? 1 : 0);
