services:
  - type: web
    name: the-card-huddle
    env: node
    buildCommand: npm install
    startCommand: node server.js
    customDomains:
      - name: thecardhuddle.com
      - name: www.thecardhuddle.com
    envVars:
      - key: SITE_URL
        value: https://thecardhuddle.com
      - key: EBAY_APP_ID
        value: PeytonFr-Pfranke-PRD-6bf52af21-03e44ad8
      - key: EBAY_CERT_ID
        sync: false
      - key: CARDSIGHTS_API_KEY
        sync: false
      - key: USE_MOCK_DATA
        value: false
      - key: AUTH_CODE
        sync: false
      - key: EBAY_VERIFICATION_TOKEN
        sync: false
